version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./data/house_prices.csv:/house_prices.csv
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    networks:
      - spark-network

  spark-master:
    image: bitnami/spark:3
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - SPARK_MODE = master
    volumes:
      - ./my_spark.py:/opt/bitnami/spark/my_spark.py
      - ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
    networks:
      - spark-network
  spark-worker-1:
    image: bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
    networks:
      - spark-network
  spark-worker-2:
      image: bitnami/spark:3
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
      volumes:
        -  ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
      networks:
        - spark-network
networks:
  spark-network:
    driver: bridge

